version: "3.9"
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: taskdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:123456@postgres:5432/taskdb
      JWT_SECRET: sua_chave_super_segura

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3001:3000"

volumes:
  pgdata:
